In [1]:
import numpy as np

In [6]:
# Crear una lista normal de python
v1 = [2,4,6]
v11 = [1,2,3]

In [7]:
# Crear un arreglo o vector de numpy
v2 = np.array([2,4,6])
v22 = np.array([1,2,3])

In [8]:
type(v1)

list

In [9]:
type(v2)

numpy.ndarray

In [10]:
v1 + v11

[2, 4, 6, 1, 2, 3]

In [11]:
v2 + v22

array([3, 6, 9])

In [13]:
# Crear un vector con unos, del tamaño que yo le indique en el argumento
v3 = np.ones(3)
v3

array([1., 1., 1.])

In [14]:
# Crear un vector dentro de un rango especificado (inicio, fin(hasta antes de))
v4 = np.arange(1,8)
v4

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
v44 = np.array([1,2,3,4,5,6,7])
v44

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Multiplicación por escalar

5 * v4

array([ 5, 10, 15, 20, 25, 30, 35])

In [17]:
5 * v1

[2, 4, 6, 2, 4, 6, 2, 4, 6, 2, 4, 6, 2, 4, 6]

In [18]:
x = np.arange(1,5)
y = np.array([2,4,6,8])

In [19]:
# Calculo del producto punto
sum(x*y)

60

In [20]:
# Calculo del producto punto con numpy
np.dot(x,y)

60

In [21]:
# Vectores Ortogonales o perpendiculares
v1 = np.array([3,4])
v2 = np.array([4,-3])

In [22]:
np.dot(v1,v2)

0

In [23]:
# Calculo de la norma con numpy
np.linalg.norm(x)

5.477225575051661

In [24]:
np.linalg.norm(v1)

5.0

In [27]:
# Creando una matriz en python
A = np.array([[1, 3, 2],
              [1, 0, 0],
              [1, 2, 2]])

In [26]:
A

array([[1, 3, 2],
       [1, 0, 0],
       [1, 2, 2]])

In [28]:
B = np.array([[1, 0, 5],[7, 5, 0],[2, 1, 1]])

In [29]:
B

array([[1, 0, 5],
       [7, 5, 0],
       [2, 1, 1]])

In [30]:
# Multiplicación de matriz por escalar
A * 2

array([[2, 6, 4],
       [2, 0, 0],
       [2, 4, 4]])

In [31]:
# Suma de matrices
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [34]:
# Resta de matrices
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [35]:
# La dimensión de la matriz
A.shape

(3, 3)

In [36]:
# La cantidad de elementos de la matriz
A.size

9

In [37]:
# Ejemplo de multiplicacion de matrices
A1 = np.arange(1, 13).reshape(3, 4)
A1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
B1 = np.arange(8).reshape(4,2)
B1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [39]:
A1 @ B1

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

In [40]:
B1 @ A1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [41]:
# Creando matriz identidad
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [42]:
A2 = np.array([[4,7],[2,6]])

In [44]:
# Multiplicación de matriz identidad
I @ A2

array([[4., 7.],
       [2., 6.]])

In [45]:
# Calcular el determinante
np.linalg.det(A2)

10.000000000000002

In [46]:
np.linalg.det(A)

-2.0

In [49]:
# Calcular la inversa
A_inv = np.linalg.inv(A2)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [50]:
A8 = np.array([[1,1,0],[2,-1,2],[0,3,0]])
A8_inv = np.linalg.inv(A8)
A8_inv

array([[ 1.        ,  0.        , -0.33333333],
       [ 0.        ,  0.        ,  0.33333333],
       [-1.        ,  0.5       ,  0.5       ]])